name: parallel
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 
        run: sleep 20

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 
        run: sleep 20

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 
        run: sleep 20

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 
        run: sleep 20
